<?php

namespace GitList\Test\Provider;

use GitList\Provider\GitServiceProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 20:17:15.
 */
class GitServiceProviderTest
    extends \PHPUnit_Framework_TestCase
{
    /**
     * @var type 
     */
    protected static $app;
    
    /**
     * @var GitServiceProvider
     */
    protected $object;

    public static function setUpBeforeClass()
    {
        self::$app = require 'boot.php';
    }
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GitServiceProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Provider\GitServiceProvider::register
     */
    public function testRegister() {
        $this->assertNull($this->object->register(self::$app));
        $this->assertInstanceOf('GitList\Git\Client', self::$app['git']);
    }

    /**
     * @covers GitList\Provider\GitServiceProvider::boot
     */
    public function testBoot() {
        $this->assertNull($this->object->boot(self::$app));
    }

}
