services:
  webserver:
    build:
      context: docker/nginx/
    depends_on:
      - php-fpm
    working_dir: /application
    volumes:
      - .:/application

  php-fpm:
    build:
      context: docker/php-fpm/
    working_dir: /application
    shm_size: 1gb
    volumes:
      - .:/application
