<?php

namespace GitList;

use org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-21 at 19:41:31.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $root = vfsStream::setup('tmp');
        $file = vfsStream::newFile('config.ini');
        $file->setContent(
            file_get_contents('config.ini') . 
            PHP_EOL . '[git]' . PHP_EOL .
            'repositories = \'vfs://tmp\''
        );
        $root->addChild($file);
        
        $this->object = new Config(vfsStream::url('tmp/config.ini'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Config::get
     */
    public function testGet() {
        $this->assertEquals(
            'vfs://tmp',
            $this->object->get('git', 'repositories')
        );
        $this->assertFalse($this->object->get('dummy', 'dummy'));
        $this->assertFalse($this->object->get('git', 'dummy'));
    }

    /**
     * @covers GitList\Config::getSection
     */
    public function testGetSection() {
        $this->assertFalse($this->object->getSection('dummy'));
        $this->assertInternalType(
            'array',
            $this->object->getSection('git')
        );
    }

    /**
     * @covers GitList\Config::set
     */
    public function testSet() {
        $this->assertNull($this->object->set('dummy', 'dummy', 'dummy'));
        $this->assertEquals(
            'dummy',
            $this->object->get('dummy', 'dummy')
        );
    }

}
