<?php

namespace GitList\Git;

use org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 20:17:25.
 */
class ClientTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Client;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Git\Client::createRepository
     */
    public function testCreateRepository() {
        $root = vfsStream::setup('tmp');
        
        $this->assertInstanceOf(
            'Gitter\Repository',
            $this->object->createRepository(vfsStream::url('tmp/repository'))
        );
            
    }
    
    /**
     * @covers GitList\Git\Client::createRepository
     */
    public function testCreateRepositoryException() {
        $this->setExpectedException('\RuntimeException');
        $root = vfsStream::setup('tmp');
        $dir = vfsStream::newDirectory('.git');
        $file = vfsStream::newFile('HEAD');
        $dir->addChild($file);
        $root->addChild($dir);
        
        $this->assertInstanceOf(
            'Gitter\Repository',
            $this->object->createRepository(vfsStream::url('tmp'))
        );
            
    }


    /**
     * @covers GitList\Git\Client::getRepository
     */
    public function testGetRepositoryException() {
        $this->setExpectedException('\RuntimeException');
        $root = vfsStream::setup('tmp');
        
        $this->assertInstanceOf(
            'Gitter\Repository',
            $this->object->getRepository(vfsStream::url('tmp/repository'))
        );
    }
}
