<?php

namespace GitList\Git;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 20:17:20.
 */
class RepositoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Repository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new Repository;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Git\Repository::getPaginatedCommits
     * @todo   Implement testGetPaginatedCommits().
     */
    public function testGetPaginatedCommits() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GitList\Git\Repository::searchCommitLog
     * @todo   Implement testSearchCommitLog().
     */
    public function testSearchCommitLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GitList\Git\Repository::searchTree
     * @todo   Implement testSearchTree().
     */
    public function testSearchTree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GitList\Git\Repository::getAuthorStatistics
     * @todo   Implement testGetAuthorStatistics().
     */
    public function testGetAuthorStatistics() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GitList\Git\Repository::getStatistics
     * @todo   Implement testGetStatistics().
     */
    public function testGetStatistics() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GitList\Git\Repository::createArchive
     * @todo   Implement testCreateArchive().
     */
    public function testCreateArchive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
