# GitList Builder: Tools to build gitlist package

## Dependencies

To use this package builder you may need to install some development packages like: dpkg-dev or evem rpm.


## How to build

The packages can be generated by running Makefile functions like:

```
$ make build_deb
$ make build_rpm
```

## Structure

Core package is a simple source package while a configuration package requires all the dependencies.

## ToDo

DONE ==
Core RPM package
Core DEB package

TODO ===
Apache Conf DEB package
Nginx Conf DEB package
Apache Conf RPM package
Nginx Conf RPM package
