<?php

namespace GitList\Test\Util;

use GitList\Util\View;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 20:14:05.
 */
class ViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new View;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Util\View::getBreadcrumbs
     */
    public function testGetBreadcrumbs() {
        $this->assertEquals(array(), $this->object->getBreadcrumbs(false));
        $this->assertEquals(
            array(
                array('dir' => 'default', 'path' => 'default'),
                array('dir' => 'home', 'path' => 'default/home'),
                array('dir' => 'index', 'path' => 'default/home/index')
            ),
            $this->object->getBreadcrumbs('default/home/index')
        );
    }

    /**
     * @covers GitList\Util\View::getPager
     */
    public function testGetPager() {
        $this->assertEquals(
            array(
                'current' => 0,
                'next' => 1,
                'previous' => -1,
                'last' => 2,
                'total' => 45
            ),
            $this->object->getPager(0, 45)
        );
    }

}
