<?php

namespace GitList\Util;

use Silex\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 19:48:35.
 */
class RepositoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Repository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Repository(new Application());;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Util\Repository::getFileType
     */
    public function testGetFileType() {
        $this->assertEquals(
            'text',
            $this->object->getFileType('plainFile')
        );
        $this->assertEquals(
            'php',
            $this->object->getFileType('boot.php')
        );
    }

    /**
     * @covers GitList\Util\Repository::getReadme
     * @todo   Implement testGetReadme().
     */
    public function testGetReadme() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
