<?php

namespace GitList\Provider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 20:17:03.
 */
class ViewUtilServiceProviderTest
    extends \PHPUnit_Framework_TestCase
{
    /**
     * @var type 
     */
    protected static $app;
    
    /**
     * @var ViewUtilServiceProvider
     */
    protected $object;

    public static function setUpBeforeClass()
    {
        self::$app = require 'boot.php';
    }
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ViewUtilServiceProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GitList\Provider\ViewUtilServiceProvider::register
     */
    public function testRegister() {
        $this->assertNull($this->object->register(self::$app));
        $this->assertInstanceOf('GitList\Util\View', self::$app['util.view']);
    }

    /**
     * @covers GitList\Provider\ViewUtilServiceProvider::boot
     */
    public function testBoot() {
        $this->assertNull($this->object->boot(self::$app));
    }

}
